# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/kcrash': '@stable'
    'frameworks/kguiaddons': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kparts': '@stable'
    'frameworks/kwidgetaddons': '@stable'
    'frameworks/kdoctools': '@stable'
    'frameworks/kdbusaddons': '@stable'
