# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
 - 'on': ['Linux/Qt5', 'FreeBSD/Qt5', 'Windows/Qt5']
   'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/kcrash': '@stable'
    'frameworks/kguiaddons': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kparts': '@stable'
    'frameworks/kwidgetsaddons': '@stable'
    'frameworks/kdoctools': '@stable'
    'frameworks/kdbusaddons': '@stable'
    'frameworks/ktextwidgets': '@stable'

 - 'on': ['Linux/Qt6', 'FreeBSD/Qt6', 'Windows/Qt6']
   'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kcrash': '@latest-kf6'
    'frameworks/kguiaddons': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kparts': '@latest-kf6'
    'frameworks/kwidgetsaddons': '@latest-kf6'
    'frameworks/kdoctools': '@latest-kf6'
    'frameworks/kdbusaddons': '@latest-kf6'
    'frameworks/ktextwidgets': '@latest-kf6'

Options:
 require-passing-tests-on: ['Linux', 'FreeBSD', 'Windows']
