/*
 * This file was generated by dbusidl2cpp version 0.5
 * when processing input file org.kde.kmplot.Kmplot.xml
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 */

#include "kmplotadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class KmplotAdaptor
 */

KmplotAdaptor::KmplotAdaptor(QObject *parent)
   : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

KmplotAdaptor::~KmplotAdaptor()
{
    // destructor
}

QString KmplotAdaptor::fileOpen()
{
    // handle method call org.kde.kmplot.Kmplot.fileOpen
    QString url;
    QMetaObject::invokeMethod(parent(), "fileOpen", Q_RETURN_ARG(QString, url));

    // Alternative:
    //url = static_cast<YourObjectType *>(parent())->fileOpen();
    return url;
}

QString KmplotAdaptor::openFileInNewWindow()
{
    // handle method call org.kde.kmplot.Kmplot.openFileInNewWindow
    QString url;
    QMetaObject::invokeMethod(parent(), "openFileInNewWindow", Q_RETURN_ARG(QString, url));

    // Alternative:
    //url = static_cast<YourObjectType *>(parent())->openFileInNewWindow();
    return url;
}

void KmplotAdaptor::optionsConfigureKeys()
{
    // handle method call org.kde.kmplot.Kmplot.optionsConfigureKeys
    QMetaObject::invokeMethod(parent(), "optionsConfigureKeys");

    // Alternative:
    //static_cast<YourObjectType *>(parent())->optionsConfigureKeys();
}

void KmplotAdaptor::optionsConfigureToolbars()
{
    // handle method call org.kde.kmplot.Kmplot.optionsConfigureToolbars
    QMetaObject::invokeMethod(parent(), "optionsConfigureToolbars");

    // Alternative:
    //static_cast<YourObjectType *>(parent())->optionsConfigureToolbars();
}

void KmplotAdaptor::setStatusBarText(const QString &text, int id)
{
    // handle method call org.kde.kmplot.Kmplot.setStatusBarText
    QMetaObject::invokeMethod(parent(), "setStatusBarText", Q_ARG(QString, text), Q_ARG(int, id));

    // Alternative:
    //static_cast<YourObjectType *>(parent())->setStatusBarText(text, id);
}


#include "kmplotadaptor.moc"
