/*
 * This file was generated by dbusidl2cpp version 0.5
 * when processing input file org.kde.kmplot.Kmplot.xml
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 */

#ifndef KMPLOTADAPTOR_H_251211149672234
#define KMPLOTADAPTOR_H_251211149672234

#include <QtCore/QObject>
#include <dbus/qdbus.h>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.kde.kmplot.Kmplot
 */
class KmplotAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.kde.kmplot.Kmplot")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.kde.kmplot.Kmplot\" >\n"
"    <method name=\"setStatusBarText\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"text\" />\n"
"      <arg direction=\"in\" type=\"i\" name=\"id\" />\n"
"    </method>\n"
"    <method name=\"optionsConfigureKeys\" />\n"
"    <method name=\"optionsConfigureToolbars\" />\n"
"    <method name=\"openFileInNewWindow\" >\n"
"      <arg direction=\"out\" type=\"s\" name=\"url\" />\n"
"    </method>\n"
"    <method name=\"fileOpen\" >\n"
"      <arg direction=\"out\" type=\"s\" name=\"url\" />\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    KmplotAdaptor(QObject *parent);
    virtual ~KmplotAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    QString fileOpen();
    QString openFileInNewWindow();
    void optionsConfigureKeys();
    void optionsConfigureToolbars();
    void setStatusBarText(const QString &text, int id);
Q_SIGNALS: // SIGNALS
};

#endif
