/*
 * This file was generated by dbusidl2cpp version 0.5
 * when processing input file org.kde.kmplot.MainDlg.xml
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 */

#ifndef MAINDLGADAPTOR_H_190431149671648
#define MAINDLGADAPTOR_H_190431149671648

#include <QtCore/QObject>
#include <dbus/qdbus.h>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.kde.kmplot.MainDlg
 */
class MainDlgAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.kde.kmplot.MainDlg")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.kde.kmplot.MainDlg\" >\n"
"    <method name=\"editAxes\" />\n"
"    <method name=\"editScaling\" />\n"
"    <method name=\"toggleShowSliders\" />\n"
"    <method name=\"slotSave\" />\n"
"    <method name=\"slotSaveas\" />\n"
"    <method name=\"slotPrint\" />\n"
"    <method name=\"slotExport\" />\n"
"    <method name=\"slotSettings\" />\n"
"    <method name=\"slotNames\" />\n"
"    <method name=\"slotCoord1\" />\n"
"    <method name=\"slotCoord2\" />\n"
"    <method name=\"slotCoord3\" />\n"
"    <method name=\"getYValue\" />\n"
"    <method name=\"findMinimumValue\" />\n"
"    <method name=\"findMaximumValue\" />\n"
"    <method name=\"graphArea\" />\n"
"    <method name=\"checkModified\" >\n"
"      <arg direction=\"out\" type=\"b\" />\n"
"    </method>\n"
"    <method name=\"isModified\" >\n"
"      <arg direction=\"out\" type=\"b\" />\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    MainDlgAdaptor(QObject *parent);
    virtual ~MainDlgAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    bool checkModified();
    void editAxes();
    void editScaling();
    void findMaximumValue();
    void findMinimumValue();
    void getYValue();
    void graphArea();
    bool isModified();
    void slotCoord1();
    void slotCoord2();
    void slotCoord3();
    void slotExport();
    void slotNames();
    void slotPrint();
    void slotSave();
    void slotSaveas();
    void slotSettings();
    void toggleShowSliders();
Q_SIGNALS: // SIGNALS
};

#endif
