/*
 * This file was generated by dbusidl2cpp version 0.5
 * when processing input file org.kde.kmplot.Parser.xml
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 */

#ifndef PARSERADAPTOR_H_20871149668202
#define PARSERADAPTOR_H_20871149668202

#include <QtCore/QObject>
#include <dbus/qdbus.h>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.kde.kmplot.Parser
 */
class ParserAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.kde.kmplot.Parser")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.kde.kmplot.Parser\" >\n"
"    <method name=\"stopDrawing\" />\n"
"    <method name=\"drawPlot\" />\n"
"  </interface>\n"
        "")
public:
    ParserAdaptor(QObject *parent);
    virtual ~ParserAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void drawPlot();
    void stopDrawing();
Q_SIGNALS: // SIGNALS
};

#endif
