/*
 * This file was generated by dbusidl2cpp version 0.5
 * when processing input file org.kde.kmplot.View.xml
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 */

#include "viewadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class ViewAdaptor
 */

ViewAdaptor::ViewAdaptor(QObject *parent)
   : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ViewAdaptor::~ViewAdaptor()
{
    // destructor
}

void ViewAdaptor::drawPlot()
{
    // handle method call org.kde.kmplot.View.drawPlot
    QMetaObject::invokeMethod(parent(), "drawPlot");

    // Alternative:
    //static_cast<YourObjectType *>(parent())->drawPlot();
}

void ViewAdaptor::stopDrawing()
{
    // handle method call org.kde.kmplot.View.stopDrawing
    QMetaObject::invokeMethod(parent(), "stopDrawing");

    // Alternative:
    //static_cast<YourObjectType *>(parent())->stopDrawing();
}


#include "viewadaptor.moc"
