/*
 * This file was generated by dbusidl2cpp version 0.5
 * when processing input file org.kde.kmplot.View.xml
 *
 * dbusidl2cpp is Copyright (C) 2006 Trolltech AS. All rights reserved.
 *
 * This is an auto-generated file.
 */

#ifndef VIEWADAPTOR_H_70641149679272
#define VIEWADAPTOR_H_70641149679272

#include <QtCore/QObject>
#include <dbus/qdbus.h>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.kde.kmplot.View
 */
class ViewAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.kde.kmplot.View")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.kde.kmplot.View\" >\n"
"    <method name=\"stopDrawing\" />\n"
"    <method name=\"drawPlot\" />\n"
"  </interface>\n"
        "")
public:
    ViewAdaptor(QObject *parent);
    virtual ~ViewAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void drawPlot();
    void stopDrawing();
Q_SIGNALS: // SIGNALS
};

#endif
